#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using TacticalPort.Data;
using UnityEditor;
using UnityEngine;

namespace TacticalPort.Editor
{
    internal static class UnitStatBudgetCatalogExporter
    {
        private const string OutputPath = "CloudCodeModules/TeamPresets/Project/UnitStatBudgetCatalog.cs";

        [MenuItem("Project/Deploy/Sync Unit Stat Budgets To Cloud Code")]
        public static void Export()
        {
            string[] lGuids = AssetDatabase.FindAssets("t:UnitDefinition", new[] { "Assets" });
            List<UnitDefinition> lUnits = new List<UnitDefinition>(lGuids.Length);
            HashSet<string> lIds = new HashSet<string>(StringComparer.Ordinal);
            for (int lIndex = 0; lIndex < lGuids.Length; lIndex++)
            {
                string lPath = AssetDatabase.GUIDToAssetPath(lGuids[lIndex]);
                UnitDefinition lUnit = AssetDatabase.LoadAssetAtPath<UnitDefinition>(lPath);
                if (lUnit == null)
                    continue;
                if (string.IsNullOrWhiteSpace(lUnit.Id) || !lIds.Add(lUnit.Id))
                    throw new InvalidOperationException($"Unit stat budget export requires unique, non-empty IDs. Invalid asset: '{lPath}'.");
                lUnits.Add(lUnit);
            }

            lUnits.Sort((pLeft, pRight) => string.CompareOrdinal(pLeft.Id, pRight.Id));
            StringBuilder lSource = new StringBuilder();
            lSource.AppendLine("// Generated by UnitStatBudgetCatalogExporter. Do not edit manually.");
            lSource.AppendLine("using System;");
            lSource.AppendLine("using System.Collections.Generic;");
            lSource.AppendLine();
            lSource.AppendLine("namespace TeamPresetsModule;");
            lSource.AppendLine();
            lSource.AppendLine("internal static class UnitStatBudgetCatalog");
            lSource.AppendLine("{");
            lSource.AppendLine("    private static readonly IReadOnlyDictionary<string, int> Budgets =");
            lSource.AppendLine("        new Dictionary<string, int>(StringComparer.Ordinal)");
            lSource.AppendLine("        {");
            for (int lIndex = 0; lIndex < lUnits.Count; lIndex++)
            {
                UnitDefinition lUnit = lUnits[lIndex];
                lSource.Append("            [\"")
                    .Append(Escape(lUnit.Id))
                    .Append("\"] = ")
                    .Append(lUnit.StatPointBudget)
                    .AppendLine(",");
            }
            lSource.AppendLine("        };");
            lSource.AppendLine();
            lSource.AppendLine("    public static bool TryGetBudget(string unitId, out int budget) => Budgets.TryGetValue(unitId, out budget);");
            lSource.AppendLine("}");

            string lAbsolutePath = Path.Combine(Directory.GetParent(Application.dataPath)!.FullName, OutputPath);
            Directory.CreateDirectory(Path.GetDirectoryName(lAbsolutePath)!);
            File.WriteAllText(lAbsolutePath, lSource.ToString(), new UTF8Encoding(false));
            Debug.Log($"Exported {lUnits.Count} unit stat budgets to '{OutputPath}'. Redeploy the TeamPresets Cloud Code module after budget changes.");
        }

        private static string Escape(string pValue) => pValue.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
#endif
