// Generated by UnitStatBudgetCatalogExporter. Do not edit manually.
using System;
using System.Collections.Generic;

namespace TeamPresetsModule;

internal static class UnitStatBudgetCatalog
{
    private static readonly IReadOnlyDictionary<string, int> Budgets =
        new Dictionary<string, int>(StringComparer.Ordinal)
        {
            ["forban"] = 120,
            ["forban_gold_decoy"] = 120,
            ["forban_heavy_gold_decoy"] = 120,
            ["simpleennemy"] = 120,
            ["simpleunit"] = 120,
            ["testunit"] = 120,
            ["unit_poutchsingle"] = 120,
        };

    public static bool TryGetBudget(string unitId, out int budget) => Budgets.TryGetValue(unitId, out budget);
}
